### ISSUE TITLE
basically nice, but can you add kubernetes integration

### ISSUE THREAD

**Issue by thraen** [mokrates/limo#1]
First of all thanks for limo. 
We implemented our inhouse erp-system with it.

**Overview**

I am proposing the implementation of Kubernetes integration to enhance limo platform's container orchestration capabilities. This integration would provide users with a seamless experience in deploying, managing, and scaling applications within Kubernetes clusters.

Currently, limo lacks native support for Kubernetes, which limits the flexibility and scalability of containerized applications. Introducing Kubernetes integration will empower users to leverage the full potential of container orchestration, taking advantage of features such as auto-scaling, rolling updates, and efficient resource utilization.

**Expected Behavior**

The integration should enable users to:

* Deploy applications directly to Kubernetes clusters from our platform.
* Monitor and manage Kubernetes resources within the platform's interface.
* Configure and customize Kubernetes-specific settings, such as namespaces, services, and ingress controllers.

**Use Case**

As a user managing microservices architecture, I find it challenging to seamlessly integrate my applications with Kubernetes for efficient scaling and resource management. This integration would simplify the deployment and orchestration process, streamlining my workflow and improving overall productivity.

**Possible Solution**

Integrate the platform with Kubernetes APIs, allowing users to connect and manage their Kubernetes clusters effortlessly. Provide an intuitive user interface for configuring Kubernetes-specific settings and monitoring resources.

**Comment by mokrates** [comment]
Thank you, ChatGPT, for faking an interest in limo.

I must, however, inform you, that kubernetes integration is not a feature to be offered by any language itself, but by a library you'd import. Which you can easily write yourself. The features you need are there:
limo already has support for sockets and, if needed, tls. json is also supported. You don't need any more to talk to the kubernetes api.

https://kubernetes.io/docs/concepts/overview/kubernetes-api/

have fun.
